services:
  ziprofs:
    # build: .
    image: ghcr.io/juniorjpdj/ziprofs@sha256:70fd5723343c532558324c01cefefb5f6d76ea8a2a341b75775e151f462016d4
    privileged: true
    volumes:
      - # Root/source directory
        source: ./data/root
        target: /app/root
        type: bind
      - # Mountpoint/target directory
        source: ./data/mnt
        target: /app/mnt
        type: bind
        bind:
          propagation: rshared
    command:
      - /app/root
      - /app/mnt
      - -o
      - allowother,foreground
